name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag ghcr.io/Siliconrob/headless-horseman:latest
        docker run ghcr.io/deselikem/hello-docker-gcr-demo:latest
        docker push ghcr.io/deselikem/hello-docker-gcr-demo:latest
